# frontend/Dockerfile.dev

# Use an official Node.js runtime as a parent image
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to leverage Docker cache
# This is important for speeding up subsequent builds
COPY package*.json ./

# Install app dependencies
RUN npm install

# Bundle app's source code
COPY . .

# Expose the Vite port
EXPOSE 5173

# Define the command to run the Vite dev server
CMD ["npm", "run", "dev", "--", "--host"]